In [1]:
import pandas as pd

acdc_ucycle_mlp_each_class = 'ACDC_metrics_for_each_class_ucycle_mlp.csv'
acdc_levit_unet_each_class = 'ACDC_metrics_for_each_class_levit_unet.csv'
acdc_swin_unet_each_class = 'ACDC_metrics_for_each_class_swin_unet.csv'
acdc_trans_unet_each_class = 'ACDC_metrics_for_each_class_trans_unet.csv'

acdc_ucycle_mlp_each_class_df = pd.read_csv('ACDC_metrics_for_each_class_ucycle_mlp.csv')
acdc_levit_unet_each_class_df = pd.read_csv('ACDC_metrics_for_each_class_levit_unet.csv')
acdc_swin_unet_each_class_df = pd.read_csv('ACDC_metrics_for_each_class_swin_unet.csv')
acdc_trans_unet_each_class_df = pd.read_csv('ACDC_metrics_for_each_class_trans_unet.csv')

In [2]:
acdc_ucycle_mlp_each_class_df

  Unnamed: 0        RV       Myo        LV
0  mean dice  0.888314  0.885549  0.957228
1       hd95  2.718600  1.010355  1.668283
2        IoU  0.806900  0.795549  0.918782
3         F1  0.888314  0.885549  0.957228

In [3]:
row_means = acdc_ucycle_mlp_each_class_df.iloc[:, 1:].mean(axis=1)

# Add the row means as a new column in the DataFrame
acdc_ucycle_mlp_each_class_df['row_mean'] = row_means

# Display the updated DataFrame with the new column
print(acdc_ucycle_mlp_each_class_df)

  Unnamed: 0        RV       Myo        LV  row_mean
0  mean dice  0.888314  0.885549  0.957228  0.910364
1       hd95  2.718600  1.010355  1.668283  1.799079
2        IoU  0.806900  0.795549  0.918782  0.840410
3         F1  0.888314  0.885549  0.957228  0.910364

In [4]:
row_means = acdc_levit_unet_each_class_df.iloc[:, 1:].mean(axis=1)

# Add the row means as a new column in the DataFrame
acdc_levit_unet_each_class_df['row_mean'] = row_means

# Display the updated DataFrame with the new column
print(acdc_levit_unet_each_class_df)

  Unnamed: 0        RV       Myo        LV  row_mean
0  mean dice  0.816853  0.804645  0.925817  0.849105
1       hd95  4.110223  2.714343  1.345565  2.723377
2        IoU  0.709688  0.678760  0.865824  0.751424
3         F1  0.816853  0.804645  0.925817  0.849105

In [5]:
row_means = acdc_swin_unet_each_class_df.iloc[:, 1:].mean(axis=1)

# Add the row means as a new column in the DataFrame
acdc_swin_unet_each_class_df['row_mean'] = row_means

# Display the updated DataFrame with the new column
print(acdc_swin_unet_each_class_df)

  Unnamed: 0         RV       Myo        LV   row_mean
0  mean dice   0.611496  0.655873  0.837258   0.701542
1       hd95  20.785162  6.832973  8.122475  11.913537
2        IoU   0.455539  0.495455  0.728484   0.559826
3         F1   0.611496  0.655873  0.837258   0.701542

In [6]:
row_means = acdc_trans_unet_each_class_df.iloc[:, 1:].mean(axis=1)

# Add the row means as a new column in the DataFrame
acdc_trans_unet_each_class_df['row_mean'] = row_means

# Display the updated DataFrame with the new column
print(acdc_trans_unet_each_class_df)

  Unnamed: 0        RV       Myo        LV  row_mean
0  mean dice  0.871750  0.862187  0.927639  0.887192
1       hd95  5.540502  1.107843  1.564125  2.737490
2        IoU  0.778032  0.759434  0.901476  0.812981
3         F1  0.871750  0.862187  0.927639  0.887192

In [7]:
import plotly.express as px
import plotly.graph_objects as go

metrics = ['Dice-Score', 'F1-Score', 'IoU-Score',]

fig = go.Figure()
fig.add_trace(go.Bar(
    x=metrics,
    y=acdc_ucycle_mlp_each_class_df['row_mean'].iloc[[0,3,2]],
    name='ucycle_mlp',
    marker_color='indianred'
))
fig.add_trace(go.Bar(
    x=metrics,
    y=acdc_levit_unet_each_class_df['row_mean'].iloc[[0,3,2]],
    name='levit_unet',
    marker_color='lightsalmon'
))
fig.add_trace(go.Bar(
    x=metrics,
    y=acdc_swin_unet_each_class_df['row_mean'].iloc[[0,3,2]],
    name='swin_unet',
    marker_color='lightblue'
))
fig.add_trace(go.Bar(
    x=metrics,
    y=acdc_trans_unet_each_class_df['row_mean'].iloc[[0,3,2]],
    name='trans_unet',
    marker_color='lightgreen'
))

# Here we modify the tickangle of the xaxis, resulting in rotated labels.
fig.update_layout(barmode='group')#, xaxis_tickangle=-45)
fig.show()

## visualtion of computational complesxity

In [8]:
models_metrics=[{
        'training_time(in hrs)': 4.5,
        'number_of_parameters': 98286248,
        'GFLOPS': 6721.30,
        'model size(in MB)' : 375.3,
        'forward pass time(in sec)': 0.0101683,
    },
    
{
        'training_time(in hrs)':  0.983 ,
        'number_of_parameters': 18913432640,
        'GFLOPS': 4699.57,
        'model size(in MB)' : 81.4,
        'forward pass time(in sec)': 0.003853321,
    },

{
        'training_time(in hrs)':  6.1167 ,
        'number_of_parameters': 43431207,
        'GFLOPS': 1467.58,
        'model size(in MB)' : 176.5,
        'forward pass time(in sec)':  0.008311033,
    },

{
        'training_time(in hrs)': 6.85,
        'number_of_parameters': 105276356,
        'GFLOPS': 4529.09,
        'model size(in MB)' : 421.3,
        'forward pass time(in sec)': 0.00642943,
    }]

In [9]:
model_metrics_df = pd.DataFrame(models_metrics)

In [10]:
model_metrics_df['models'] = ['UCycle_Mlp', 'Levit_Unet', 'Swin_Unet', 'Trans_Unet']
model_metrics_df

,training_time(in hrs),number_of_parameters,GFLOPS,model size(in MB),forward pass time(in sec),models
0,4.5000,98286248,6721.30,375.3,0.010168,UCycle_Mlp
1,0.9830,18913432640,4699.57,81.4,0.003853,Levit_Unet
2,6.1167,43431207,1467.58,176.5,0.008311,Swin_Unet
3,6.8500,105276356,4529.09,421.3,0.006429,Trans_Unet

In [11]:

fig = px.scatter(model_metrics_df, y="training_time(in hrs)", x="models", )
# fig.update_traces(marker_size=10)
fig.update_traces(marker=dict(size=12, symbol='diamond', color='orange', line=dict(width=2,)))
fig.update_layout(
    title="Model Training Time Comparison",
    xaxis_title="Models",
    yaxis_title="Training Time (in hours)",
    # template="plotly_light",  # Dark theme
    showlegend=False,  # Remove legend if not needed
    xaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
    yaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
)
fig.show()

In [12]:

fig = px.scatter(model_metrics_df, y="GFLOPS", x="models", )
# fig.update_traces(marker_size=10)
fig.update_traces(marker=dict(size=12, symbol='diamond', color='green', line=dict(width=2,)))
fig.update_layout(
    title="GFLOPS Comparison",
    xaxis_title="Models",
    yaxis_title="GFLOPS",
    # template="plotly_light",  # Dark theme
    showlegend=False,  # Remove legend if not needed
    xaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
    yaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
)
fig.show()

In [13]:

fig = px.scatter(model_metrics_df, y="forward pass time(in sec)", x="models", )
# fig.update_traces(marker_size=10)
fig.update_traces(marker=dict(size=12, symbol='diamond', color='brown', line=dict(width=2,)))
fig.update_layout(
    title="Forward Pass Time Comparison",
    xaxis_title="Models",
    yaxis_title="Forward Pass Time(in Sec)",
    # template="plotly_light",  # Dark theme
    showlegend=False,  # Remove legend if not needed
    xaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
    yaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
)
fig.show()

In [14]:

fig = px.scatter(model_metrics_df, y="model size(in MB)", x="models", )
# fig.update_traces(marker_size=10)
fig.update_traces(marker=dict(size=12, symbol='diamond', color='yellow', line=dict(width=2,)))
fig.update_layout(
    title="Model Size Comparison",
    xaxis_title="Models",
    yaxis_title="Model Size in MB)",
    # template="plotly_light",  # Dark theme
    showlegend=False,  # Remove legend if not needed
    xaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
    yaxis=dict(showgrid=True, zeroline=False),  # Show grid lines
)
fig.show()

In [15]:


fig = go.Figure(data=[go.Table(
    header=dict(values=['Models', 'No of Parameters'],
                line_color='darkslategray',
                # fill_color='lightskyblue',
                align='left'),
    cells=dict(values=[model_metrics_df['models'], # 1st column
                       ['98.28 M', '18.91 B', '43.43 M', '105.27 M']], # 2nd column
               line_color='darkslategray',
            #    fill_color='lightcyan',
               align='left'))
])

fig.update_layout(width=500, height=300)
fig.show()